### ISSUE TITLE
run_predict on new dataframe without values for response

### ISSUE THREAD

**Issue by shivakhanal** [choonghyunryu/alookr#1]
Hi,

Following the example in `alookr` package. 

library(dplyr)
sb <- rpart::kyphosis %>%   split_by(Kyphosis)
train <- sb %>%   extract_set(set = "train")
test <- sb %>%   extract_set(set = "test")
result <- run_models(.data = train, target = "Kyphosis", positive = "present")
pred <- run_predict(result, test)

_But when try to predict on dataset without the response variable, it does not work_
pred <- run_predict(result, test[, -1])

The error message is `Error: Can't extract columns that don't exist.
x Column `Kyphosis` doesn't exist.`

I would appreciate any support. 

Thanks,
Shiva

**Comment by choonghyunryu** [comment]
Hi, Mr. Shiva

Thanks for your presented problem.
I'll release a version that fixes the problem soon.

Thanks,
Choonghyun
