### ISSUE TITLE
Column `var2` is NULL

### ISSUE THREAD

**Issue by camnesia** [choonghyunryu/alookr#6]
I am trying to run a simple `treatment_corr()` on _alookr 0.3.7._ 

```
library(alookr)

example <- data.frame(val1 = c(1.2, 2.2, 3, 5),
                      val2 = c(1.7, 2.3, 3, 4),
                      val3 = c(9, 4, 1, 7))

treatment_corr(example)
```
Resulting in an odd error.

![image](https://user-images.githubusercontent.com/19314038/183666130-66517183-2f55-40e0-be8b-ea01eb906c4f.png)

**Comment by choonghyunryu** [comment]
@camnesia,

I am very sorry for being late. 
I have put the development version that fixes the error on Github.
